### Nearest Neighbor classifier demo

Very simple example of a nn classifier.

In [2]:
import numpy as np

In [3]:
class NearestNeighborClassifier:
    """
    Very simple NN classifier written in numpy.
    """

    def __init__(self):
        pass

    def train(self, X, y):
        """
        Remembers all the training data.

        X is (N x D) training data, each row is an example.
        y is 1 dimension of size N and contains the labels.
        """
        self.Xtr = X
        self.ytr = y

    def predict(self, X):
        """
        Finds the nearest training image to the i'th test image.
        Uses L1 distance.

        X is (N x D) examples for prediction.
        """
        num_test = X.shape[0]
        Ypred = np.zeros(num_test, dtype=self.ytr.dtype)

        # loop over all test rows and compute L1 distance
        for i in range(num_test):
            distances = np.sum(np.abs(self.Xtr - X[i, :]), axis=1)
            min_index = np.argmin(distances)
            # now we can get the label of the nearest example
            Ypred[i] = self.ytr[min_index]

        return Ypred

In [5]:
# create some artificial data
data = [np.random.random((1, 3)) + offset for offset in range(3)]
X = np.vstack(data)
X

array([[0.82095139, 0.06914682, 0.45645868],
       [1.17034272, 1.13949591, 1.6997633 ],
       [2.06780303, 2.12844919, 2.04703132]])

In [6]:
# create some labels for data
y = np.arange(0, 3).reshape(3, 1)
y

array([[0],
       [1],
       [2]])

In [9]:
# create and train the classifier
nn = NearestNeighborClassifier()
nn.train(X, y)

In [8]:
# create some test examples and find their nearest neighbor
Xtest = np.array(([3, 3, 3], [0, 0, 0]))
nn.predict(Xtest)

array([2, 0])